config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    #名前は必須入力かつ20文字以内
    validates :name , length: { maximum: 20} , presence: true
    #年齢は、一文字以上、整数、0以上を記載
    validates :age , length: {minimum: 1 } , numericality: {only_integer: true, greater_than_or_equal_to: 0} 
    #内容は必須入力かつ2文字以上30文字以下
    validates :body , length: {minimum: 2 , maximum: 30} , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
#フォームで入力されたパラメータを受け取りデータベースへ保存する
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def index
    #Messageをすべて取得する。
    @messages=Message.all
    @message=Message.new
  end
  
  def edit
  end
  
  #削除アクション
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  #アップデートアクション
  def update
    if @message.update(message_params)
      #保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました。'
    else
      #保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  ##ここから表記（フォームで入力された内容を保存するためのインスタンスを作成）
  #その後、.saveでメッセージモデルのインスタンスをDBに保存する
  def create
    @message=Message.new(message_params)
    if    @message.save
      #ルートURLにリダイレクトする
      redirect_to root_path , notice: 'メッセージを保存しました。'
    else
      #メッセージが保存できなかった場合（Message.saveでfalseが返ってくる）は
      #入力画面に戻し（render 'index'）、再度入力を促す
      @messages=Message.all
      flash.now[:alert]="メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
  ##ココから下はprivateメソッドとなる
  private
  def message_params
    #params[:message]のパラメータでname, body,ageのみ許可する
    #返り値はex:){name:"入力されたname",age:"入力されたage",body:"入力されたbody"}
    params.require(:message).permit(:name, :age, :body)
  end
  ##ここまで
  
  def set_message
    @message=Message.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<% #レイアウトテンプレートを使用し、デザインやコンポーネントの共通化を行う %>
<% #以下の処理によりTwitter BootstrapのCSSを読み込むことができる %>
<!DOCTYPE html>
<html>
<head>
  <title>みんなの掲示板</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<% #投稿フォームを記述 %>

<%= form_for(@message) do |f| %>
    <% #エラーメッセージを表示するための部分 %>
    <% if @message.errors.present? %>
    <div class="alert alert-danger">
        <%= alert %>
        <ul>
            <% @message.errors.full_messages.each do |full_message| %>
            <li>
                <%= full_message %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>
    
    <% #メッセージ投稿フォーム %>
        <div class="form-group">
            <%= f.label:Name,{class:'col-sm-1'} %>
            <div class="col-sm-11">
                <%= f.text_field :name, :class=>'form-control', :size=>7 %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label:Age,{class:'col-sm-1'} %>
            <div class="col-sm-11">
                <%= f.text_field :age, :class=>'form-control', :size=>7 %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :"Comment", {class:'col-sm-1'} %>
            <div class="col-sm-11">
                <%= f.text_area :body, :class=>'form-control', :cols=>20, :rows=>10 %>
            </div>
        </div>
        <div class="col-sm-offset-1 col-sm-11">
            <%= f.submit class:"btn btn-sm btn-info" %>
        </div>
        </div>
    
    
    <% end %>

app/views/messages/edit.html.erb
<% #(edit)リンクを押されたときに表示するためのフォームを作成 %>
<h1>メッセージの編集</h1>
<%= render 'form' %>

app/views/messages/index.html.erb
<% #投稿されたフォーム内容を表示するボードを記載 %>
<div class="panel panel-info">
    <div class="panel-heading">
        メッセージ一覧
    </div>
    
    <div class="panel-body">
        <% #テーブル形式で名前、年齢、コメントを表示 %>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Comments</th>
                </tr>
            </thead>
            <tbody>
                <% @messages.each do |message| %>
                <tr>
                    <th><span class="label label-info"><%= message.name %></span></th>
                    <td><%= message.age %></td>
                    <td><%= message.body %>　
                    <% #編集、削除を行うためのフォームにリンク %>
                    (<%= link_to "edit", edit_message_path(message) %>)
                    (<%= link_to "destroy", message, method: :delete, data: {confirm: '削除してもよろしいですか？' } %>)</td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
    
    <% #部分テンプレートを読み込んでいる %>
    <%= render 'form' %>